#! /bin/sh -
#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#
# Example 1. Compile README.adoc into README.html.
#
#       adock README.adoc
#
# Example 2. Compile README.adoc into README.pdf.
#
#       adock -b pdf -r asciidoctor-pdf README.adoc
#
# Example 3. Compile README.adoc into README.html, running docker with
# sudo.
#
#       DOCKER='sudo docker' adock README.adoc
#
# Example 4. Continuously recompile README.adoc into HTML and serve it
# through an HTTP server listening on 0.0.0.0:8000.
#
#       adock --serve README.adoc
#
# Example 5. Pull the latest version of the quinngrier/adock Docker
# image.
#
#       adock --pull
#

LC_ALL=C
readonly LC_ALL
export LC_ALL

detach=
unset http_addr
image=quinngrier/adock
unset live_addr
unset name
pull=false

# TODO: Use gatbps_parse_opt for options parsing.

while :; do

  case ${1-} in --)
    shift
    break
  esac

  case ${1-} in --detach)
    detach=-d
    shift
    continue
  esac

  case ${1-} in --image)
    case ${2+x} in '')
      printf '%s\n' "$0: Option requires an argument: $1" >&2
      exit 1
    esac
    image=$1=$2
    shift 2
    case $# in 0)
      set x "$image"
    ;; *)
      set x "$image" "$@"
    esac
    shift
    continue
  esac

  case ${1-} in --image=*)
    case $1 in *[!-.0-9:=A-Z_a-z]*)
      printf '%s\n' "$0: Invalid option argument: $1" >&2
      exit 1
    esac
    r='[^=]*=\(.*\)'
    image=`expr "x$1" : "x$r"` || exit $?
    shift
    continue
  esac

  case ${1-} in --name)
    case ${2+x} in '')
      printf '%s\n' "$0: Option requires an argument: $1" >&2
      exit 1
    esac
    name=$1=$2
    shift 2
    case $# in 0)
      set x "$name"
    ;; *)
      set x "$name" "$@"
    esac
    shift
    continue
  esac

  case ${1-} in --name=*)
    case $1 in *[!-.0-9=A-Z_a-z]*)
      printf '%s\n' "$0: Invalid option argument: $1" >&2
      exit 1
    esac
    r='[^=]*=\(.*\)'
    name=`expr "x$1" : "x$r"` || exit $?
    shift
    continue
  esac

  case ${1-} in --pull)
    pull=:
    shift
    continue
  esac

  case ${1-} in --serve)
    http_addr=0.0.0.0:8000
    live_addr=0.0.0.0:35729
    shift
    continue
  esac

  case ${1-} in --serve=*)
    case $1 in *[!-,.0-9:=A-Z_a-z]*)
      printf '%s\n' "$0: Invalid option argument: $1" >&2
      exit 1
    esac
    r='[^=]*=\(.*\)'
    http_addr=`expr "x$1" : "x$r"` || exit $?
    case $http_addr in *,*)
      r='.*,\(.*\)'
      live_addr=`expr "x$http_addr" : "x$r"` || exit $?
      r='\(.*\),.*'
      http_addr=`expr "x$http_addr" : "x$r"` || exit $?
    ;; *)
      live_addr=35729
    esac
    case $http_addr in *:*)
      :
    ;; *)
      http_addr=0.0.0.0:$http_addr
    esac
    case $live_addr in *:*)
      :
    ;; *)
      r='\(.*\):.*'
      live_addr=`expr "x$http_addr" : "x$r"`:$live_addr || exit $?
    esac
    shift
    continue
  esac

  break

done

readonly detach
readonly http_addr
readonly image
readonly live_addr
readonly name
readonly pull

docker=${DOCKER:-docker}
readonly docker

if $pull; then
  eval " $docker"' pull "$image"' || exit $?
  exit
fi

test -t 0 && s=0 || s=$?
case $s in 0)
  t=-t
;; 1)
  t=
;; *)
  exit $s
esac
readonly t

u=`id -u` || exit $?
readonly u

g=`id -g` || exit $?
readonly g

pwd=`pwd` || exit $?
readonly pwd

args='run --rm -i $t $detach -u $u:$g -v "$pwd:$pwd" -w "$pwd"'
case ${http_addr+x} in ?*)
  args=$args' -p "$http_addr:80" -p "$live_addr:35729"'
esac
case ${name+x} in ?*)
  args=$args' --name "$name"'
esac
args=$args' "$image"'
case ${http_addr+x} in ?*)
  args=$args' --serve "$http_addr" "$live_addr"'
esac
readonly args

case $# in 0)
  eval " $docker $args" || exit $?
;; *)
  eval " $docker $args"' "$@"' || exit $?
esac
