//
// The authors of this file have waived all copyright and
// related or neighboring rights to the extent permitted by
// law as described by the CC0 1.0 Universal Public Domain
// Dedication. You should have received a copy of the full
// dedication along with this file, typically as a file
// named <CC0-1.0.txt>. If not, it may be available at
// <https://creativecommons.org/publicdomain/zero/1.0/>.
//

= adock(1)
:doctype: manpage

== Name

adock - run asciidoctor in a docker container

== Synopsis

*adock* [<__option__>]... [**--**] [<__argument__>]...

== Description

*adock* runs *asciidoctor* inside a Docker container with the given
<__argument__>s and performs additional processing as specified by the
<__option__>s.
The current working directory is mounted into the container and used as
the current working directory inside the container so that all files
below the current working directory can be accessed.
The container runs with the current user ID and group ID so that any
files it outputs will have the appropriate ownership.

== Options

**--detach**::
Run the container in the background instead of the foreground.
This options corresponds to the *-d*/*--detach* option of *docker run*.

**--serve**[**=**<__address__>]::
Instead of yielding the output files, *adock* will instead collect them
into a temporary directory and run an HTTP server to serve them.
