//
// The authors of this file have waived all copyright and
// related or neighboring rights to the extent permitted by
// law as described by the CC0 1.0 Universal Public Domain
// Dedication. You should have received a copy of the full
// dedication along with this file, typically as a file
// named <CC0-1.0.txt>. If not, it may be available at
// <https://creativecommons.org/publicdomain/zero/1.0/>.
//

= Adock

Adock is a link:https://docs.docker.com/[Dockerized] version of
link:https://docs.asciidoctor.org/asciidoctor/latest/[Asciidoctor] that
allows you to compile and preview Asciidoctor documents without needing
anything but Docker.
Here's how to get started:

. {empty}
Download the link:adock[`adock`] shell script from this repository and
put it anywhere in your
link:https://en.wikipedia.org/wiki/PATH_(variable)[`PATH`].

. {empty}
To compile a document `foo.adoc` into `foo.html`, run `adock foo.adoc`.

. {empty}
To preview a document `foo.adoc`, run `adock --serve foo.adoc` and open
`++http://127.0.0.1:8000++` in a browser.
The page will automatically refresh as you edit the document.

. {empty}
To update Adock, redownload the link:adock[`adock`] shell script from
this repository and additionally run `adock --pull`.

//
