//
// The authors of this file have waived all copyright and
// related or neighboring rights to the extent permitted by
// law as described by the CC0 1.0 Universal Public Domain
// Dedication. You should have received a copy of the full
// dedication along with this file, typically as a file
// named <CC0-1.0.txt>. If not, it may be available at
// <https://creativecommons.org/publicdomain/zero/1.0/>.
//

= Adock
:experimental:

:download_url: https://raw.githubusercontent.com/quinngrier/adock/master/adock
:man_page_url: https://github.com/quinngrier/adock/blob/master/adock.adoc

:x_Asciidoctor_Diagram_url: https://github.com/asciidoctor/asciidoctor-diagram
:x_Asciidoctor_Diagram: link:{x_Asciidoctor_Diagram_url}[Asciidoctor Diagram,window=_blank]

:x_asciidoctor_url: https://docs.asciidoctor.org/asciidoctor/latest/cli/man1/asciidoctor/
:x_asciidoctor: link:{x_asciidoctor_url}[asciidoctor,window=_blank]

:x_asciidoctor_r_url: https://docs.asciidoctor.org/asciidoctor/latest/cli/man1/asciidoctor/
:x_asciidoctor_r: link:{x_asciidoctor_r_url}[-r,window=_blank]

:x_fill_url: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill
:x_fill: link:{x_fill_url}[fill,window=_blank]

:x_red_url: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value
:x_red: link:{x_red_url}[red,window=_blank]

:x_style_url: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/style
:x_style: link:{x_style_url}[style,window=_blank]

:x_tspan_url: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/tspan
:x_tspan: link:{x_tspan_url}[tspan,window=_blank]

Adock is a Dockerized version of Asciidoctor that lets you compile and
preview Asciidoctor documents without installing anything but Docker.

Here's how to get started:

. {empty}
link:{download_url}[Click here to download the `adock` shell script.]
The script is portable enough to run on any Unix-like system that has
Docker installed.
You can put the script anywhere you like, but the rest of these steps
will assume that you've put it somewhere in your `PATH`.

. {empty}
Run `echo 'Hello, world!' >foo.adoc` to create a simple Asciidoctor
document, then run `adock foo.adoc` to compile it into `foo.html`.

. {empty}
Run `adock -s foo.adoc` to do the same thing as the previous step, but
this time also running an HTTP server on `0.0.0.0:8000` to preview the
document.
Open `++http://127.0.0.1:8000++` in a browser and click on `foo.html` to
view the document.
The document will be automatically recompiled and your browser will
automatically refresh as you make changes to `foo.adoc`.
When you're done, press kbd:[Ctrl+C] to stop and remove the Docker
container.

. {empty}
Run `adock -ds foo.adoc` to do the same thing as the previous step, but
this time running the Docker container in the background instead of the
foreground.
When you're done, run `docker rm -f adock` to stop and remove the Docker
container.

. {empty}
Run `adock -u` to pull the latest version of the Docker image and
download and replace `adock` itself with the latest version of `adock`.

. {empty}
link:{man_page_url}[Click here to view the full man page for `adock`.]

== Diagram support

{x_Asciidoctor_Diagram} can be enabled using the `{x_asciidoctor_r}`
option of `{x_asciidoctor}` with `asciidoctor-diagram` as the argument.
For example:
`adock {x_asciidoctor_r} asciidoctor-diagram foo.adoc`.

The following diagram types are supported:

* {empty}
link:https://www.bpmn.org/[BPMN,window=_blank]
(link:https://raw.githubusercontent.com/quinngrier/adock/master/test/diagram/bpmn/index.adoc[example,window=_blank])

* {empty}
link:https://graphviz.org/[Graphviz,window=_blank]
(link:https://raw.githubusercontent.com/quinngrier/adock/master/test/diagram/graphviz/index.adoc[example,window=_blank])

* {empty}
link:https://pikchr.org/[Pikchr,window=_blank]
(link:https://raw.githubusercontent.com/quinngrier/adock/master/test/diagram/pikchr/index.adoc[example,window=_blank])

** {empty}
Pikchr is
link:patches/pikchr.patch[patched]
to allow `\<` and `\>` escapes to be used in strings, which emit `<` and
`>` directly into the SVG code instead of `&amp;gt;` and `&amp;lt;`.
This allows SVG tags such as `<{x_tspan}>` to be used.
For example:
`box "\<{x_tspan} {x_style}=\"{x_fill}: {x_red}\"\>foo\</{x_tspan}\>"`.

//
