//
// The authors of this file have waived all copyright and
// related or neighboring rights to the extent permitted by
// law as described by the CC0 1.0 Universal Public Domain
// Dedication. You should have received a copy of the full
// dedication along with this file, typically as a file
// named <CC0-1.0.txt>. If not, it may be available at
// <https://creativecommons.org/publicdomain/zero/1.0/>.
//

= Adock
:experimental:

Adock is a link:https://docs.docker.com/[Dockerized] version of
link:https://docs.asciidoctor.org/asciidoctor/latest/[Asciidoctor] that
lets you compile and preview Asciidoctor documents without installing
anything but Docker.

Here's how to get started:

. {empty}
Download the link:adock[`adock`] shell script from this repository.
The script is portable enough to run in any POSIX-like shell.

. {empty}
Run `adock foo.adoc` to compile any document `foo.adoc` into `foo.html`.

. {empty}
Run `adock -s foo.adoc` to compile any document `foo.adoc` into
`foo.html` and run an HTTP server on `0.0.0.0:8000` for previewing.
The document will be automatically recompiled and your browser will
automatically refresh as you make changes.
Press kbd:[Ctrl+C] to stop the server.

. {empty}
Run `adock -u` to pull the latest Docker image and download and replace
the `adock` shell script with the latest version.

. {empty}
Refer to the full man page for the `adock` shell script at
link:adock.adoc[`adock.adoc`].

//
