//
// The authors of this file have waived all copyright and
// related or neighboring rights to the extent permitted by
// law as described by the CC0 1.0 Universal Public Domain
// Dedication. You should have received a copy of the full
// dedication along with this file, typically as a file
// named <CC0-1.0.txt>. If not, it may be available at
// <https://creativecommons.org/publicdomain/zero/1.0/>.
//

= Adock
:experimental:

:download_url: https://raw.githubusercontent.com/quinngrier/adock/master/adock
:man_page_url: https://github.com/quinngrier/adock/blob/master/adock.adoc

Adock is a Dockerized version of Asciidoctor that lets you compile and
preview Asciidoctor documents without installing anything but Docker.

Here's how to get started:

. {empty}
link:{download_url}[Click here to download the `adock` shell script.]
The script is portable enough to run on any Unix-like system that has
Docker installed.
You can put the script anywhere you like, but the rest of these steps
will assume that you've put it somewhere in your `PATH`.

. {empty}
Run `echo 'Hello, world!' >foo.adoc` to create a simple Asciidoctor
document, then run `adock foo.adoc` to compile it into `foo.html`.

. {empty}
Run `adock -s foo.adoc` to do the same thing as the previous step, but
this time also running an HTTP server on `0.0.0.0:8000` to preview the
document.
Open `++http://127.0.0.1:8000++` in a browser and click on `foo.html` to
view the document.
The document will be automatically recompiled and your browser will
automatically refresh as you make changes to `foo.adoc`.
When you're done, press kbd:[Ctrl+C] to stop and remove the Docker
container.

. {empty}
Run `adock -ds foo.adoc` to do the same thing as the previous step, but
this time running the Docker container in the background instead of the
foreground.
When you're done, run `docker rm -f adock` to stop and remove the Docker
container.

. {empty}
Run `adock -u` to pull the latest version of the Docker image and
download and replace `adock` itself with the latest version of `adock`.

. {empty}
link:{man_page_url}[Click here to view the full man page for `adock`.]

== Diagram support

link:https://github.com/asciidoctor/asciidoctor-diagram[Asciidoctor Diagram]
can be enabled with the `-r asciidoctor-diagram` option.

[cols=".^a,.^a,.^a"]
|===

| link:https://www.bpmn.org/[BPMN]
| link:https://raw.githubusercontent.com/quinngrier/adock/master/test/diagram/bpmn/index.adoc[Example code]
| image::https://github.com/quinngrier/adock/actions/workflows/test-diagram-bpmn.yml/badge.svg[BPMN test result]

| link:https://graphviz.org/[Graphviz]
| link:https://raw.githubusercontent.com/quinngrier/adock/master/test/diagram/graphviz/index.adoc[Example code]
| image::https://github.com/quinngrier/adock/actions/workflows/test-diagram-graphviz.yml/badge.svg[Graphviz test result]

| link:https://pikchr.org/[Pikchr]
| link:https://raw.githubusercontent.com/quinngrier/adock/master/test/diagram/pikchr/index.adoc[Example code]
| image::https://github.com/quinngrier/adock/actions/workflows/test-diagram-pikchr.yml/badge.svg[Pikchr test result]

|===

//
