#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#

#
# This workflow periodically force pushes an empty orphan commit to the
# keepalive branch to prevent the following behaviors:
#
#     * If the repository is inactive for too long, scheduled
#       GitHub Actions may be disabled.
#

name: keepalive

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  keepalive:
    name: keepalive
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Create and push the commit
        run: |
          git config user.name keepalive || exit $?
          git config user.email keepalive || exit $?
          git rm "*" || exit $?
          x=`git write-tree` || exit $?
          x=`git commit-tree -m keepalive ${x?}` || exit $?
          git push -f origin ${x?}:refs/heads/keepalive || exit $?
