#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#

#
# This workflow periodically resets the GitHub Actions inactivity timer,
# which would otherwise disable all scheduled workflows after a certain
# period of repository inactivity.
#

name: Reset inactivity

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  keepalive:
    name: Reset inactivity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: keepalive
      - name: Create an empty commit
        run: |
          git config user.name \
            'Quinn Grier (via GitHub Actions)' \
          || exit $?
          git config user.email \
            'quinn@quinngrier.com' \
          || exit $?
          git commit \
            --allow-empty \
            -m 'Reset the GitHub Actions inactivity timer' \
          || exit $?
      - name: Push the empty commit
        run: |
          git push || exit $?
