#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#

#
# This workflow periodically pushes and deletes a tag to prevent the
# following behaviors:
#
#     * If the repository is inactive for too long, scheduled
#       GitHub Actions may be disabled.
#

name: keepalive

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  keepalive:
    name: keepalive
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Push and delete a tag
        run: |
          t=keepalive${GITHUB_RUN_ID?}
          git tag ${t?} || exit $?
          git push origin ${t?}:refs/tags/${t?} || exit $?
          git push origin :refs/tags/${t?} || exit $?
