#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#

name: Test the Pikchr diagram support

on:
  workflow_run:
    types:
      - completed
    workflows:
      - Build and push the Docker image

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Test the Pikchr diagram support
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run test script
        run: bash test/diagram.bash pikchr
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: test/diagram/pikchr/**
